shared:
    image: node:8

parameters:
    region: "us-west-1"
    az:
        value: "1"
        description: "default availability zone"

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - param_values1: meta get parameters
            - param_values2: meta get parameters.region
            - param_values3: meta get parameters.az
            - meta: meta get -j parameters
